package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class customerDistance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String booking_id;

	private String translator_id;

	private int distance;

	private int eta;

	public customerDistance() {
	}

	public java.lang.String getBooking_id() {
		return this.booking_id;
	}

	public void setBooking_id(java.lang.String booking_id) {
		this.booking_id = booking_id;
	}

	public java.lang.String getTranslator_id() {
		return this.translator_id;
	}

	public void setTranslator_id(java.lang.String translator_id) {
		this.translator_id = translator_id;
	}

	public int getDistance() {
		return this.distance;
	}

	public void setDistance(int distance) {
		this.distance = distance;
	}

	public int getEta() {
		return this.eta;
	}

	public void setEta(int eta) {
		this.eta = eta;
	}

	public customerDistance(java.lang.String booking_id,
			java.lang.String translator_id, int distance, int eta) {
		this.booking_id = booking_id;
		this.translator_id = translator_id;
		this.distance = distance;
		this.eta = eta;
	}

}