package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class language implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;

	private java.lang.Long user_id;

	private java.lang.Long language_id;

	private java.lang.Long translator_level_id;

	private java.lang.String created_at;

	private java.lang.String updated_at;

	public language() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getUser_id() {
		return this.user_id;
	}

	public void setUser_id(java.lang.Long user_id) {
		this.user_id = user_id;
	}

	public java.lang.Long getLanguage_id() {
		return this.language_id;
	}

	public void setLanguage_id(java.lang.Long language_id) {
		this.language_id = language_id;
	}

	public java.lang.Long getTranslator_level_id() {
		return this.translator_level_id;
	}

	public void setTranslator_level_id(java.lang.Long translator_level_id) {
		this.translator_level_id = translator_level_id;
	}

	public java.lang.String getCreated_at() {
		return this.created_at;
	}

	public void setCreated_at(java.lang.String created_at) {
		this.created_at = created_at;
	}

	public java.lang.String getUpdated_at() {
		return this.updated_at;
	}

	public void setUpdated_at(java.lang.String updated_at) {
		this.updated_at = updated_at;
	}

	public language(java.lang.Long id, java.lang.Long user_id,
			java.lang.Long language_id, java.lang.Long translator_level_id,
			java.lang.String created_at, java.lang.String updated_at) {
		this.id = id;
		this.user_id = user_id;
		this.language_id = language_id;
		this.translator_level_id = translator_level_id;
		this.created_at = created_at;
		this.updated_at = updated_at;
	}

}